<h3 align="center">$\mathbb{A}\vec{x} = \vec{b}$</h3> 


<h3 align="center">$
\begin{pmatrix}
2 & 1 & 4 & 1\\
3 & 4 & -1 & -1\\
1 & -4 & 1 & 5\\
2 & -2 & 1 & 3\\
\end{pmatrix}
  \begin{align}
    \begin{pmatrix}
           w \\
           x \\
           y \\
           z 
    \end{pmatrix}
    =
    \begin{pmatrix}
           -4 \\
           3 \\
           9 \\
           7 
         \end{pmatrix}
  \end{align}
$</h3> 

In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

In [2]:

# Matriz que representa el sistema a resolver
A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)


v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver


## Eliminación Gussiana

In [15]:
v = np.array([ -4, 3, 9, 7 ],float)  # Vector del sistema a resolver
N = len(v)   #dimension

A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)


# Eliminacion Gaussiana
for m in range(N):
    
    # Localizo el elemento a pivotear
    div = A[m,m]    
    A[m,:] /= div  # divido el renglon que toca entre su pivote    
    v[m] /= div      # También dividimos al vector del sistema por el pivote

    for i in range(m+1,N):
        mult = A[i,m]          #encontramos el elemento por el que debemos multiplicar
        A[i,:] = A[i,:] - mult*A[m,:]   # y multiplicamo el renglon por dicho numero y se lo restamos al renglón de abajo
        v[i] = v[i] - mult*v[m]        # hacemos las mismas operaciones para el vector de resultados     
        
        

############ Una vez "triangulizada" la matriz  realizamos el  Backsubstitution

x = np.empty(N,float)  #definimos unvector x vacio

for m in range(N-1,-1,-1):
    x[m] = v[m]               #asignamos a x el valor del ultimo elemento
    # print(x)
    for i in range(m+1,N):
        x[m] -= A[m,i]*x[i]
# print("********************************")    

In [18]:
print("A = \n",A)
print("-----------------")
print("\n x = ",x)

A = 
 [[ 1.   0.5  2.   0.5]
 [ 0.   1.  -2.8 -1. ]
 [-0.  -0.   1.  -0. ]
 [-0.  -0.  -0.   1. ]]
-----------------

 x =  [ 2. -1. -2.  1.]


In [22]:
A = np.array([[ 2,  1,  4,  1 ],
           [ 3,  4, -1, -1 ],
           [ 1, -4,  1,  5 ],
           [ 2, -2,  1,  3 ]],float)

P,L,U = sp.linalg.lu(A)

In [23]:
LU = np.dot(L,U)
LU

array([[ 3.,  4., -1., -1.],
       [ 1., -4.,  1.,  5.],
       [ 2.,  1.,  4.,  1.],
       [ 2., -2.,  1.,  3.]])

In [26]:
np.dot(P,LU)

array([[ 2.,  1.,  4.,  1.],
       [ 3.,  4., -1., -1.],
       [ 1., -4.,  1.,  5.],
       [ 2., -2.,  1.,  3.]])